// <auto-generated />
using System;
using Dirakitin.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Dirakitin.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240112235041_KelasMigration")]
    partial class KelasMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Dirakitin.Models.Dosen", b =>
                {
                    b.Property<string>("NIP")
                        .HasMaxLength(18)
                        .HasColumnType("varchar(18)");

                    b.Property<string>("Alamat")
                        .HasColumnType("longtext");

                    b.Property<string>("Nama")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("NIP");

                    b.ToTable("Dosen");
                });

            modelBuilder.Entity("Dirakitin.Models.KelasMengajar", b =>
                {
                    b.Property<int>("IdKelas")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("DosenNIP")
                        .HasColumnType("varchar(18)");

                    b.Property<DateTime>("Jadwal")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("MataKuliahKodeMK")
                        .HasColumnType("varchar(255)");

                    b.HasKey("IdKelas");

                    b.HasIndex("DosenNIP");

                    b.HasIndex("MataKuliahKodeMK");

                    b.ToTable("KelasMengajar");
                });

            modelBuilder.Entity("Dirakitin.Models.Mahasiswa", b =>
                {
                    b.Property<string>("NIM")
                        .HasMaxLength(12)
                        .HasColumnType("varchar(12)");

                    b.Property<string>("Alamat")
                        .HasColumnType("longtext");

                    b.Property<string>("Jurusan")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nama")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("NIM");

                    b.ToTable("Mahasiswa");
                });

            modelBuilder.Entity("Dirakitin.Models.MataKuliah", b =>
                {
                    b.Property<string>("KodeMK")
                        .HasColumnType("varchar(255)");

                    b.Property<byte>("JumlahSKS")
                        .HasColumnType("tinyint unsigned");

                    b.Property<string>("Keterangan")
                        .HasColumnType("longtext");

                    b.Property<string>("Nama")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("KodeMK");

                    b.ToTable("MataKuliah");
                });

            modelBuilder.Entity("Dirakitin.Models.KelasMengajar", b =>
                {
                    b.HasOne("Dirakitin.Models.Dosen", "Dosen")
                        .WithMany("Kelas")
                        .HasForeignKey("DosenNIP");

                    b.HasOne("Dirakitin.Models.MataKuliah", "MataKuliah")
                        .WithMany("Kelas")
                        .HasForeignKey("MataKuliahKodeMK");

                    b.Navigation("Dosen");

                    b.Navigation("MataKuliah");
                });

            modelBuilder.Entity("Dirakitin.Models.Dosen", b =>
                {
                    b.Navigation("Kelas");
                });

            modelBuilder.Entity("Dirakitin.Models.MataKuliah", b =>
                {
                    b.Navigation("Kelas");
                });
#pragma warning restore 612, 618
        }
    }
}
